CRITICAL - 2022-08-18 13:41:25 --> Class "CodeIgniter\Model\UsuarioModel" not found
in APPPATH\Controllers\Auth.php on line 16.
 1 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Auth->autenticar()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-08-18 13:43:43 --> Class "App\Model\UsuarioModel" not found
in APPPATH\Controllers\Auth.php on line 16.
 1 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Auth->autenticar()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-08-18 17:17:33 --> syntax error, unexpected token "*", expecting end of file
in APPPATH\Config\Routes.php on line 45.
 1 SYSTEMPATH\CodeIgniter.php(406): CodeIgniter\CodeIgniter->tryToRouteIt(null)
 2 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-08-18 17:17:36 --> syntax error, unexpected token "*", expecting end of file
in APPPATH\Config\Routes.php on line 45.
 1 SYSTEMPATH\CodeIgniter.php(406): CodeIgniter\CodeIgniter->tryToRouteIt(null)
 2 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-08-18 18:33:50 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\Controle-de-Gastos\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\Controle-de-Gastos\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\Controle-de-Gastos\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Controle-de-Gastos\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Controle-de-Gastos\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\Controle-de-Gastos\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Controle-de-Gastos\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Controle-de-Gastos\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\Controle-de-Gastos\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\Controle-de-Gastos\app\Models\UsuarioModel.php(30): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\Controle-de-Gastos\app\Controllers\Cadastro.php(34): App\Models\UsuarioModel->create(Array)
#10 C:\xampp\htdocs\Controle-de-Gastos\system\CodeIgniter.php(898): App\Controllers\Cadastro->create()
#11 C:\xampp\htdocs\Controle-de-Gastos\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cadastro))
#12 C:\xampp\htdocs\Controle-de-Gastos\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\Controle-de-Gastos\index.php(67): CodeIgniter\CodeIgniter->run()
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\Controle-de-Gastos\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\Controle-de-Gastos\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Controle-de-Gastos\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Controle-de-Gastos\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\Controle-de-Gastos\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\Controle-de-Gastos\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\Controle-de-Gastos\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\Controle-de-Gastos\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\Controle-de-Gastos\app\Models\UsuarioModel.php(30): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\Controle-de-Gastos\app\Controllers\Cadastro.php(34): App\Models\UsuarioModel->create(Array)
#9 C:\xampp\htdocs\Controle-de-Gastos\system\CodeIgniter.php(898): App\Controllers\Cadastro->create()
#10 C:\xampp\htdocs\Controle-de-Gastos\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cadastro))
#11 C:\xampp\htdocs\Controle-de-Gastos\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Controle-de-Gastos\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-08-18 18:33:50 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuario` (`email`, `senha`, `nome`) VALUES (:email:, :senha:, :nome:)', [...], false)
 3 SYSTEMPATH\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(738): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(666): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(658): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Models\UsuarioModel.php(30): CodeIgniter\BaseModel->save([...])
 8 APPPATH\Controllers\Cadastro.php(34): App\Models\UsuarioModel->create([...])
 9 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Cadastro->create()
10 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cadastro))
11 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-08-18 18:35:36 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\Controle-de-Gastos\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\Controle-de-Gastos\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\Controle-de-Gastos\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Controle-de-Gastos\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Controle-de-Gastos\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\Controle-de-Gastos\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Controle-de-Gastos\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Controle-de-Gastos\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\Controle-de-Gastos\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\Controle-de-Gastos\app\Models\UsuarioModel.php(30): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\Controle-de-Gastos\app\Controllers\Cadastro.php(34): App\Models\UsuarioModel->create(Array)
#10 C:\xampp\htdocs\Controle-de-Gastos\system\CodeIgniter.php(898): App\Controllers\Cadastro->create()
#11 C:\xampp\htdocs\Controle-de-Gastos\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cadastro))
#12 C:\xampp\htdocs\Controle-de-Gastos\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\Controle-de-Gastos\index.php(67): CodeIgniter\CodeIgniter->run()
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\Controle-de-Gastos\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\Controle-de-Gastos\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Controle-de-Gastos\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Controle-de-Gastos\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\Controle-de-Gastos\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\Controle-de-Gastos\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\Controle-de-Gastos\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\Controle-de-Gastos\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\Controle-de-Gastos\app\Models\UsuarioModel.php(30): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\Controle-de-Gastos\app\Controllers\Cadastro.php(34): App\Models\UsuarioModel->create(Array)
#9 C:\xampp\htdocs\Controle-de-Gastos\system\CodeIgniter.php(898): App\Controllers\Cadastro->create()
#10 C:\xampp\htdocs\Controle-de-Gastos\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cadastro))
#11 C:\xampp\htdocs\Controle-de-Gastos\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Controle-de-Gastos\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-08-18 18:35:36 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuario` (`email`, `senha`, `nome`) VALUES (:email:, :senha:, :nome:)', [...], false)
 3 SYSTEMPATH\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(738): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(666): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(658): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Models\UsuarioModel.php(30): CodeIgniter\BaseModel->save([...])
 8 APPPATH\Controllers\Cadastro.php(34): App\Models\UsuarioModel->create([...])
 9 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Cadastro->create()
10 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cadastro))
11 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-08-18 18:36:42 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\Controle-de-Gastos\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\Controle-de-Gastos\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('127.0.0.1', 'root', 'root', 'controlegastos', 3306, '', 0)
#1 C:\xampp\htdocs\Controle-de-Gastos\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Controle-de-Gastos\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Controle-de-Gastos\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\Controle-de-Gastos\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Controle-de-Gastos\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Controle-de-Gastos\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\Controle-de-Gastos\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\Controle-de-Gastos\app\Models\UsuarioModel.php(30): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\Controle-de-Gastos\app\Controllers\Cadastro.php(34): App\Models\UsuarioModel->create(Array)
#10 C:\xampp\htdocs\Controle-de-Gastos\system\CodeIgniter.php(898): App\Controllers\Cadastro->create()
#11 C:\xampp\htdocs\Controle-de-Gastos\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cadastro))
#12 C:\xampp\htdocs\Controle-de-Gastos\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\Controle-de-Gastos\index.php(67): CodeIgniter\CodeIgniter->run()
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\Controle-de-Gastos\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\Controle-de-Gastos\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Controle-de-Gastos\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Controle-de-Gastos\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\Controle-de-Gastos\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\Controle-de-Gastos\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\Controle-de-Gastos\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\Controle-de-Gastos\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\Controle-de-Gastos\app\Models\UsuarioModel.php(30): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\Controle-de-Gastos\app\Controllers\Cadastro.php(34): App\Models\UsuarioModel->create(Array)
#9 C:\xampp\htdocs\Controle-de-Gastos\system\CodeIgniter.php(898): App\Controllers\Cadastro->create()
#10 C:\xampp\htdocs\Controle-de-Gastos\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cadastro))
#11 C:\xampp\htdocs\Controle-de-Gastos\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Controle-de-Gastos\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-08-18 18:36:42 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuario` (`email`, `senha`, `nome`) VALUES (:email:, :senha:, :nome:)', [...], false)
 3 SYSTEMPATH\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(738): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(666): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(658): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Models\UsuarioModel.php(30): CodeIgniter\BaseModel->save([...])
 8 APPPATH\Controllers\Cadastro.php(34): App\Models\UsuarioModel->create([...])
 9 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Cadastro->create()
10 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cadastro))
11 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-08-18 19:04:19 --> Attempt to assign property "exists" on array
in APPPATH\Models\UsuarioModel.php on line 18.
 1 APPPATH\Controllers\Auth.php(35): App\Models\UsuarioModel->login([...])
 2 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Auth->autenticar()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-08-18 19:06:10 --> Attempt to read property "idUsuario" on array
in APPPATH\Controllers\Auth.php on line 39.
 1 APPPATH\Controllers\Auth.php(39): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "idUsuario" on array', 'APPPATH\\Controllers\\Auth.php', 39)
 2 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Auth->autenticar()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
