ERROR - 2022-08-20 17:44:05 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\controle\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\controle\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('127.0.0.1', 'root', '', 'controlegastos', 3306, '', 0)
#1 C:\xampp\htdocs\controle\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\controle\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\controle\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\controle\system\Model.php(249): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\controle\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\controle\app\Models\UsuarioModel.php(17): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\controle\app\Controllers\Auth.php(35): App\Models\UsuarioModel->login(Array)
#8 C:\xampp\htdocs\controle\system\CodeIgniter.php(898): App\Controllers\Auth->autenticar()
#9 C:\xampp\htdocs\controle\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp\htdocs\controle\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\controle\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\controle\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\controle\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\controle\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\controle\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\controle\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\controle\system\Model.php(249): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\controle\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\controle\app\Models\UsuarioModel.php(17): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\controle\app\Controllers\Auth.php(35): App\Models\UsuarioModel->login(Array)
#7 C:\xampp\htdocs\controle\system\CodeIgniter.php(898): App\Controllers\Auth->autenticar()
#8 C:\xampp\htdocs\controle\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\controle\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\controle\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\controle\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2022-08-20 17:44:05 --> Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuario`
WHERE `email` = :email:
AND `senha` = :senha:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(249): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(622): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\UsuarioModel.php(17): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Auth.php(35): App\Models\UsuarioModel->login([...])
 7 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Auth->autenticar()
 8 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 9 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-08-20 17:44:36 --> Arquivo inválido: .php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('.php')
 2 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('ROOTPATH\\public', [], true)
 3 APPPATH\Controllers\Controle.php(7): view('ROOTPATH\\public')
 4 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Controle->index()
 5 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controle))
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-08-20 17:45:06 --> Arquivo inválido: .php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('.php')
 2 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('ROOTPATH\\public', [], true)
 3 APPPATH\Controllers\Controle.php(7): view('ROOTPATH\\public')
 4 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Controle->index()
 5 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Controle))
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
